### ISSUE TITLE
Update matejsvajger/ntlm-soap-client

### ISSUE THREAD

**Issue by vincentchalamon** [vincentchalamon/nav-bundle#7]
Waiting for https://github.com/matejsvajger/ntlm-soap-client/pull/7 & new release

**Comment by GregoireHebert** [comment]
you could even use the http client for that.
https://github.com/symfony/symfony/pull/32231

**Comment by vincentchalamon** [comment]
But the http-client does not support SOAP...
Maybe this could be a better alternative: https://github.com/jamesiarmes/php-ntlm

**Comment by GregoireHebert** [comment]
:(
might be

**Comment by vincentchalamon** [comment]
I think I'll create my own client directly in this bundle...
